### ISSUE TITLE
would you please provide the two camera video？

### ISSUE THREAD

**Issue by gogov5** [ckjellson/tt_tracker#1]
I want to try the demo, would you please provide the two camera video?

by the way,  which position of  the two camera?   along the table?    a  picture will be helpful, thanks

**Comment by ckjellson** [comment]
1. You can run the demo without videos, it only uses the saved ball-positions in each camera in the "data"-folder.
2. Look at the camera arrows in the first and fifth README image. The exact position and direction is not important.

**Comment by gogov5** [comment]
> 1. You can run the demo without videos, it only uses the saved ball-positions in each camera in the "data"-folder.
> 2. Look at the camera arrows in the first and fifth README image. The exact position and direction is not important.

thank you for your quick reply, I will try as your tips
