### ISSUE TITLE
Both Camera Positions

### ISSUE THREAD

**Issue by git-hamza** [ckjellson/tt_tracker#4]
First of all great work.

I have managed to replicate your code as you have provided the relevant data. I still couldn't find what was the position of both cameras that are capturing the ball trajectories (in comparison to the court).

If you can either provide a sample video or point me in the direction of the position of both cameras with respect to the court.

**Comment by ckjellson** [comment]
Thanks!

If I understand correctly you are looking for the positions of the cameras in the demo. These are calculated in the Analyzer class during plotting using the factorizations A1 and A2 of the camera matrices (line 306-307). Hope this helps!

**Comment by tiwarisnehil** [comment]
please provide sample video from both angles about what you are trying to convey about camera position as fast as possible.

**Comment by ckjellson** [comment]
I am not going to upload the videos in the demo if that is what you are asking.
The cameras should currently be placed somewhere on one side of the table each, and then the camera matrices will be calculated when you mark the six points of the table in the videos. These matrices include information about the camera positions relative to the table, and the positions are currently only extracted (calculated) from the camera matrices during plotting, as mentioned above.

**Comment by tiwarisnehil** [comment]
Ill try again and let you know. The code sometimes made py1 py2 files and
didnt make other trajectory files in the data folder
Maybe the video is an issue
Thanks for the reply
